modLoader="javafml"
loaderVersion="[33,)"
license="MIT License"
[[mods]]
modId="vm"
version="${file.jarVersion}"
displayName="Vending Machine"
displayURL="https://www.curseforge.com/minecraft/mc-mods/vending-machine"
logoFile="logo.png"
authors="Lupicus, MacTso"
description='''Vending Machine Mod'''
[[dependencies.vm]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.vm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,1.17)"
    ordering="NONE"
    side="BOTH"
